export default {
login: "Zriyaz",
id: 48159525,
node_id: "MDQ6VXNlcjQ4MTU5NTI1",
avatar_url: "https://avatars0.githubusercontent.com/u/48159525?v=4",
gravatar_id: "",
url: "https://api.github.com/users/Zriyaz",
html_url: "https://github.com/Zriyaz",
followers_url: "https://api.github.com/users/Zriyaz/followers",
following_url: "https://api.github.com/users/Zriyaz/following{/other_user}",
gists_url: "https://api.github.com/users/Zriyaz/gists{/gist_id}",
starred_url: "https://api.github.com/users/Zriyaz/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/Zriyaz/subscriptions",
organizations_url: "https://api.github.com/users/Zriyaz/orgs",
repos_url: "https://api.github.com/users/Zriyaz/repos",
events_url: "https://api.github.com/users/Zriyaz/events{/privacy}",
received_events_url: "https://api.github.com/users/Zriyaz/received_events",
type: "User",
site_admin: false,
name: "Md Riyaz Kazmi",
company: "KONGU ENGINEERING COLLEGE",
blog: "www.kongu.ac.in",
location: "Chennai",
email: null,
hireable: null,
bio: "“When you wake up in the morning you have two choices: go back to sleep, or wake up and chase those dreams.”",
twitter_username: "riyaz_kazmi",
public_repos: 51,
public_gists: 0,
followers: 1,
following: 13,
created_at: "2019-03-02T16:42:42Z",
updated_at: "2020-07-20T12:56:40Z"
}
